### PR TITLE
Mobile And Desktop Popup

### PR DESCRIPTION
**Pull request by ciarangapu**
The following were made
-Created a new branch and named it mobile menu dropdown.
-Added a file and named it script.js.
-Run linters errors.
-Implemented the popup of mobile and desktop.

### CODE REVIEW

**Review by NalianAchei2020 — CHANGES_REQUESTED** [review]
- [x] Please ensure that the buttons on the popup are visible in the desktop version. You can add overflow scrolling if necessary.
image

**Comment by NalianAchei2020** [comment]
Hi @ciarangapu 

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

You're Almost there, funny one eyed alien

## Highlights
- Nice UI design.
- No linter errors


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review.**

**Comment by NalianAchei2020** [comment]
- [x] Please ensure that the buttons on the popup are visible in the desktop version. You can add overflow scrolling if necessary.
image

**Review by NalianAchei2020 — CHANGES_REQUESTED** [review]
- [x] Please adjust the close icon in both the mobile and desktop versions. The icon is slightly misaligned and not positioned correctly on the image.
image

**Review by NalianAchei2020 — APPROVED** [review]
# STATUS: APPROVED 🟢 👏
### Hi @ciarangapu 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: .
Congratulations! 🎉 Keep up the good work 🥂

Now you can merge this branch and move on 🥇
Happy Coding cheers 🥇 💯

**Review by Afu-Phina — COMMENTED** [review]
Hi @ciarangapu , Congratulations for the job well done. You did a great job implementing the mobile and desktop popup.   🥰 😎 😊 

However I noticed in your [README.md file](https://github.com/ciarangapu/Ciara_portfolio_website/blob/a70474286cb6a9391b89238b89aa5ab2e7c0b20d/README.md) you pasted the the live deployment link [here](https://github.com/ciarangapu/Ciara_portfolio_website/blob/a70474286cb6a9391b89238b89aa5ab2e7c0b20d/README.md?plain=1#L131) under the LICENSE heading which is inappropriate. Please put it under the Deployment heading and if it doesn't exist please add it.

Feel free to contact me in case of any need.
Happy Coding!!

**Pull request merged**
